<?php
/*
 * The dashboard module tests out setting up a block using the block API and
 * rendering some content in the block using a renderable array.
*/

// TODO make table for dashboard block instance data, so that each block
//   has its own config parameters. Currently they are shared, using the
//   {variable} table.

/*
	Queries needed for dashboard block instances
		replacing variable_get
			'#default_value' => variable_get('var', 'default_value'),
				get the saved value for the var from the mbid row in the dashboard
				table, using a query (db_merge). multiblock assigns a serial delta.
		replacing variable_set
			variable set('var');
				use db_update query to alter the value in the dashboard table, using
				a join with multiblock and/or block.
*/

/*
 * Implements hook_block_info().
*/
function dashboard_block_info() {
/*
 * $blocks[] Defines the blocks controlled by this module.
*/
	$blocks['multigraph_dashboard'] = array(
		'info' => t('Multigraph Dashboard'),
		'status' => TRUE,
		'region' => 'content',
		'weight' => 0,
		'visibility' => 1,
		'mb_enabled' => TRUE,
	);
	
	return $blocks;
}

/*
 * Implements hook_block_configure().
*/
function dashboard_block_configure($delta) {
	$form = array();
//	dsm('dashboard_block_configure hook run');
	switch ($delta) {
		case 'multigraph_dashboard':
	/* Variables needed
			$width
			$height
			$swf_path
			$config_path
		Set variables: variable_set($name, $value)
		Get variables: variable_get($name, $default = NULL)
		Set default (in block config form): '#default_value' => variable_get($name, $default = NULL),
	*/
// TODO block_configure seems to be loading the defaults and overriding the
//		values from the table

      $record = db_query('SELECT m.dashboard_delta, m.dashboard_width,
        m.dashboard_height, m.dashboard_swf_path, m.dashboard_config_path
        FROM {multigraph_dashboard} m WHERE m.dashboard_delta=:delta', array(':delta' => $delta))->fetchAssoc();

			// Enables multiblock instance configuration saving
			$form['multiblock_delta'] = array(
				'#type' => 'value',
				'#value' => $block_id,
			);

// '#default_value' => isset($record['dashboard_width']) ? $record['dashboard_width'] : variable_get('dashboard_width'),
			$form['width'] = array(
				'#type' => 'textfield',
				'#title' => 'Dashboard Width',
				'#description' => 'Set the width for the multigraph dashboard.',
//				'#default_value' => variable_get('dashboard_width', '534'),
				'#default_value' => isset($record['dashboard_width']) ? $record['dashboard_width'] : variable_get('dashboard_width'),

			);

			$form['height'] = array(
				'#type' => 'textfield',
				'#title' => 'Dashboard Height',
				'#description' => 'Set the height for the multigraph dashboard.',
//				'#default_value' => variable_get('dashboard_height', '700'),
        '#default_value' => isset($record['dashboard_height']) ? $record['dashboard_height'] : variable_get('dashboard_height'), 

			);

			// Gets the default path to the .swf file
			$swf_path = drupal_get_path('module', 'dashboard') . "/Dashboard.swf";
		
			$form['swf_path'] = array(
				'#type' => 'textfield',
				'#title' => 'Dashboard swf Path',
				'#description' => 'Set the path to the flash swf file.',
//				'#default_value' => variable_get('dashboard_swf_path', $swf_path),
        '#default_value' => isset($record['dashboard_swf_path']) ? $record['dashboard_swf_path'] : variable_get('dashboard_swf_path'),

			);

			// The default config path for the mugl
			$config_path = "http://dashboard.nemac.org/sites/default/files/versions/2012-07-06/data/dashboard.xml";

			$form['config_path'] = array(	
				'#type' => 'textfield',
				'#title' => 'Dashboard Config Path',
				'#description' => 'Set the config path for the mugl (multigraph xml file).',
//				'#default_value' => variable_get('dashboard_config_path', $config_path)d
        '#default_value' => isset($record['dashboard_config_path']) ? $record['dashboard_config_path'] : variable_get('dashboard_config_path'),

			);
			break;
	}
	return $form;
}	

/* using the filter
		$form['mugl_data'] = array(
			'#type' => 'textarea',
			'#title' => 'Configure mugl data',
			'#rows' => 10,
			'#cols' => 10,
			'#description' => 'Paste the mugl data to display in the block.',
			'#default_value' => '',
		);
			break;
		// Selects previously entered value
		$mugl_query = db_query("SELECT mugl FROM {dashboard_mugl} WHERE mgid = :mgid", array(':mgid' => 1) )->fetchField();
		$form['mugl'] = array(
			'#type' => 'text_format',
			'#title' => 'Mugl data file',
			'#format' => 'full_html_and_multigraph',
			'#description' => 'Reference a mugl file using the "Full HTML and multigraph" input format.',
			'#default_value' => $mugl_query,
		);
		$form['mugl_description'] = array(
		);
		$form['mugl_swf'] = array(
		);
		$form['mugl_nid'] = array(
		);

		break;
	}
	return $form; 
} */

/*
 * Implements hook_block_save().
*/
function dashboard_block_save($delta ='', $edit = array()) {
	if ($delta == 'multigraph_dashboard') {
//			dsm($edit);
			// Setting the dashboard variables from form values
/* replacing with query
			variable_set('dashboard_width', $edit['width']);
			variable_set('dashboard_height', $edit['height']);
			variable_set('dashboard_swf_path', $edit['swf_path']);
			variable_set('dashboard_config_path', $edit['config_path']);
		// replace the variable_set's with a drupal_write_record() or db_merge()
*/
		$record = array(
			'dashboard_delta' => $delta,
			'dashboard_width' => $edit['width'],
			'dashboard_height' => $edit['height'],
			'dashboard_swf_path' => $edit['swf_path'],
			'dashboard_config_path' => $edit['config_path'],
			'module' => 'dashboard', // Ideally use query result here
		);	

		$table = 'multigraph_dashboard';
		drupal_write_record($table, $record);
	}	

/*
	if ($edit['orig_delta'] == 'multigraph_dashboard') {
	// put query for multiblock dashboard blocks here
	}
*/
}

/*
 * Implements hook_block_view().
*/
function dashboard_block_view($delta = '') {
//			dsm('Hello world');
	switch($delta) {
		case 'multigraph_dashboard':
			//dsm('Hello world');
//			$block['subject'] = 'Mugl Dashboard';
			$block['content'] = dashboard_contents($delta);	
			// Enables multiblock instance configuration saving
			$block['multiblock_delta'] = array(
				'#type' => 'value',
				'#value' => $block_id,
			);

//			$block['content'] = array('#markup' => 'This is where the Mugl Dashboard should go.');
			return $block;
		break;
	}
}

/*
 * Custom function to render the 'mugl' field.
*/
function dashboard_contents($delta) {
	switch($delta) {
		case 'multigraph_dashboard':

			// Initializing config variables
			$record = db_query('SELECT m.dashboard_delta, m.dashboard_width,
				m.dashboard_height, m.dashboard_swf_path, m.dashboard_config_path
				FROM {multigraph_dashboard} m WHERE m.dashboard_delta=:delta', array(':delta' => $delta))->fetchAssoc();
			$width = $record['dashboard_width'];
			$height =  $record['dashboard_height'];
      $swf_path = $record['dashboard_swf_path'];
      $config_path = $record['dashboard_config_path'];
/* Switching to using multigraph_dashboard table
			$swf_path_default = drupal_get_path('module', 'dashboard') . "Dashboard.swf"; 
			$width = variable_get('dashboard_width', "534");
			$height = variable_get('dashboard_height', "700");
			$swf_path = variable_get('dashboard_swf_path', "$swf_path_default");
			$config_path = variable_get('dashboard_config_path', "http://dashboard.nemac.org/sites/default/files/versions/2012-07-06/data/dashboard.xml");
*/
			// Returning the object to be rendered inside block
			return array('#markup' => <<<EOF
<object
  id="Global Climate Dashboard"
  classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
  width="$width"
  height="$height"
  codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0">
    <param name="align" value="middle" />
    <param name="allowScriptAccess" value="sameDomain" />
    <param name="allowFullScreen" value="false" />
    <param name="quality" value="best" />
    <param name="scale" value="exactfit" />
    <param name="wmode" value="opaque" />
    <param name="bgcolor" value="#ffffff" />
    <param name="src" value="$swf_path" />
    <param name="flashvars" value="config=$config_path" />
    <param name="name" value="Global Climate Dashboard" />
<embed
  id="Global Climate Dashboard"
  type="application/x-shockwave-flash"
  width="$width"
  height="$height"
  src="$swf_path"
  name="Global Climate Dashboard"
  bgcolor="#ffffff"
  wmode="opaque"
  scale="exactfit"
  quality="best"
  flashvars="config=$config_path"
  allowfullscreen="false"
  allowscriptaccess="sameDomain"
  align="middle">
</embed>
</object>
EOF
);

/*			// Returning the object to be rendered inside block
			return array('#markup' => <<<EOF
<object
  id="Global Climate Dashboard"
  classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
  width="534"
  height="700"
  codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0">
    <param name="align" value="middle" />
    <param name="allowScriptAccess" value="sameDomain" />
    <param name="allowFullScreen" value="false" />
    <param name="quality" value="best" />
    <param name="scale" value="exactfit" />
    <param name="wmode" value="opaque" />
    <param name="bgcolor" value="#ffffff" />
    <param name="src" value="/jmarchesmg/sites/all/modules/dashboard/Dashboard.swf" />
    <param name="flashvars" value="config=http://dashboard.nemac.org/sites/default/files/versions/2012-07-06/data/dashboard.xml" />
    <param name="name" value="Global Climate Dashboard" />
<embed
  id="Global Climate Dashboard"
  type="application/x-shockwave-flash"
  width="534"
  height="700"
  src="/jmarchesmg/sites/all/modules/dashboard/Dashboard.swf"
  name="Global Climate Dashboard"
  bgcolor="#ffffff"
  wmode="opaque"
  scale="exactfit"
  quality="best"
  flashvars="config=http://dashboard.nemac.org/sites/default/files/versions/2012-07-06/data/dashboard.xml"
  allowfullscreen="false"
  allowscriptaccess="sameDomain"
  align="middle">
</embed>
</object>
EOF
); */
			break;
	}
}
